name: MobCoinCore
version: '1'
main: com.czrbyn.mobCoinCore.MobCoinCore
api-version: '1.21'
commands:
  mobcoin:
    aliases:
      - mobcoins
      - mcoin
      - mcoins
    description: description